// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertClicks implements pgx.CopyFromSource.
type iteratorForInsertClicks struct {
	rows                 []InsertClicksParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertClicks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertClicks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LinkID,
		r.rows[0].VariantID,
		r.rows[0].ClientID,
		r.rows[0].VideoID,
		r.rows[0].TrakyoID,
		r.rows[0].IpHash,
		r.rows[0].UserAgent,
		r.rows[0].Referrer,
		r.rows[0].Country,
		r.rows[0].DeviceType,
		r.rows[0].Browser,
		r.rows[0].Os,
		r.rows[0].IsBot,
	}, nil
}

func (r iteratorForInsertClicks) Err() error {
	return nil
}

// Bulk insert for the async batch writer (pgx CopyFrom).
func (q *Queries) InsertClicks(ctx context.Context, arg []InsertClicksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"clicks"}, []string{"link_id", "variant_id", "client_id", "video_id", "trakyo_id", "ip_hash", "user_agent", "referrer", "country", "device_type", "browser", "os", "is_bot"}, &iteratorForInsertClicks{rows: arg})
}
