// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID         pgtype.UUID
	LinkID     pgtype.UUID
	TrakyoID   string
	IpHash     pgtype.Text
	UserAgent  pgtype.Text
	GeoCountry pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type Client struct {
	ID                  pgtype.UUID
	WorkspaceID         pgtype.UUID
	Name                string
	YoutubeRefreshToken pgtype.Text
	CreatedAt           pgtype.Timestamptz
}

type Conversion struct {
	ID            pgtype.UUID
	TrakyoID      pgtype.Text
	EventType     string
	RevenueAmount pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type TrackingLink struct {
	ID        pgtype.UUID
	ClientID  pgtype.UUID
	Slug      string
	TargetUrl string
	CreatedAt pgtype.Timestamptz
}

type Workspace struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}
