// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLinkBySlug = `-- name: GetLinkBySlug :one
SELECT id, target_url FROM tracking_links WHERE slug = $1 LIMIT 1
`

type GetLinkBySlugRow struct {
	ID        pgtype.UUID
	TargetUrl string
}

func (q *Queries) GetLinkBySlug(ctx context.Context, slug string) (GetLinkBySlugRow, error) {
	row := q.db.QueryRow(ctx, getLinkBySlug, slug)
	var i GetLinkBySlugRow
	err := row.Scan(&i.ID, &i.TargetUrl)
	return i, err
}

const insertClick = `-- name: InsertClick :exec
INSERT INTO clicks (link_id, trakyo_id, ip_hash, user_agent)
VALUES ($1, $2, $3, $4)
`

type InsertClickParams struct {
	LinkID    pgtype.UUID
	TrakyoID  string
	IpHash    pgtype.Text
	UserAgent pgtype.Text
}

func (q *Queries) InsertClick(ctx context.Context, arg InsertClickParams) error {
	_, err := q.db.Exec(ctx, insertClick,
		arg.LinkID,
		arg.TrakyoID,
		arg.IpHash,
		arg.UserAgent,
	)
	return err
}
